### ISSUE TITLE
i am use this package in laravel its generate error code and error are in the description

### ISSUE THREAD

**Issue by sajid9** [short-pixel-optimizer/shortpixel-php#11]
ShortPixel\fromFile("resources/assets/images/home_images/1553067689watch.jpg")->toFiles("resources/assets/images/home_images/compressed");

error comming "continue" targeting switch is equivalent to "break". Did you mean to use "continue 2"

**Comment by sajid9** [comment]
ShortPixel\fromFile("resources/assets/images/home_images/1553067689watch.jpg")->toFiles("resources/assets/images/home_images/compressed");

error comming "continue" targeting switch is equivalent to "break". Did you mean to use "continue 2"

**Comment by zaherg** [comment]
can you show the full code that you have wrote?

**Comment by short-pixel-optimizer** [comment]
could you please provide a stack trace? I can't find the offending continue.

**Comment by usman-topdot** [comment]
here is the screenshot of error
http://prntscr.com/oayamu
It's still showing error

**"continue" targeting switch is equivalent to "break". Did you mean to use "continue 2"**

I tried to update the package using composer but it's still same

**Note: I am using Laravel**
