### ISSUE TITLE
Syntax errors in the README

### ISSUE THREAD

**Issue by yellow1912** [short-pixel-optimizer/shortpixel-php#12]
There are various php syntax errors in the readme.

**Comment by yellow1912** [comment]
example:

`count($ret->->succeeded)`

**Comment by short-pixel-optimizer** [comment]
Fixed with https://github.com/short-pixel-optimizer/shortpixel-php/commit/ae0bfb5c8dc2d30ba103cb91f8dfb7b69f8fb80a

**Comment by short-pixel-optimizer** [comment]
Thanks @yellow1912 !
