### ISSUE TITLE
"continue" targeting switch is equivalent to "break". Did you mean to use "continue 2"?

### ISSUE THREAD

**Issue by usman-topdot** [short-pixel-optimizer/shortpixel-php#13]
Hi, I am trying to use ShortPixel API and when I hit it I receive the following exception.
Here is the attached ScreenShot, http://prntscr.com/obxg7t

Also here is the screenshot of code snippet of Client.php line 306, http://prntscr.com/obxgl3

**Comment by short-pixel-optimizer** [comment]
This is fixed but I can't find now the exact version when it was fixed...
