### ISSUE TITLE
Does not work in PHP 5.3.3

### ISSUE THREAD

**Issue by reygimo** [short-pixel-optimizer/shortpixel-php#14]
There are errors in PHP 5.3.3 because of the array dereferencing.

Example in lib\ShortPixel\persist\PNGMetadataExtractor.php :

$chunk_size = unpack( "N", $buf )[1];

This is the error:

Parse error: syntax error, unexpected '[' in /shortpixel-php-1.5.6/lib/ShortPixel/persist/PNGMetadataExtractor.php on line 78

This only supports PHP 5.4 >=

**Comment by short-pixel-optimizer** [comment]
Could you please check with the released 1.6.1? Thanks!
