### ISSUE TITLE
Problem in PHP version 7.4.1

### ISSUE THREAD

**Issue by andreluizsr90** [short-pixel-optimizer/shortpixel-php#15]
PHP Deprecated:  Unparenthesized `a ? b : c ? d : e` is deprecated. Use either `(a ? b : c) ? d : e` or `a ? b : (c ? d : e)` in /var/www/job/vendor/shortpixel/shortpixel-php/lib/ShortPixel/Result.php on line 375

**Comment by short-pixel-optimizer** [comment]
Fixed with commit https://github.com/short-pixel-optimizer/shortpixel-php/commit/e64a31717e1542b912f48eaff303ab0f7e11e703
