### ISSUE TITLE
Very large .pack file

### ISSUE THREAD

**Issue by ecotechie** [short-pixel-optimizer/shortpixel-php#16]
There is a very large .pack file of 80MB + on this repo... Is it necessary?

git verify-pack -v .git/objects/pack/pack-256283c59ac76707b9689466b1b37dde483491cf.pack

**Comment by short-pixel-optimizer** [comment]
@ecotechie thanks for the heads up, but I can't find this pack on my local, running the command returns:

fatal: Cannot open existing pack file '.git/objects/pack/pack-256283c59ac76707b9689466b1b37dde483491cf.idx'
.git/objects/pack/pack-256283c59ac76707b9689466b1b37dde483491cf.pack: bad

**Comment by ecotechie** [comment]
That may not be the exact file name, but a large .pack file should be there under the .git/objects/pack/ directory.

**Comment by short-pixel-optimizer** [comment]
My .git/objects/pack/ folder is empty... so you can safely delete it.

**Comment by short-pixel-optimizer** [comment]
Please let me know and reopen if anything bad happens after deleting.
