### ISSUE TITLE
Warning in Client.php

### ISSUE THREAD

**Issue by csaggo** [short-pixel-optimizer/shortpixel-php#18]
At line 70 in Client.php there is often times a PHP-Warning "invalid argument supplied for foreeach"

The reason is that $body is not necessarly an array. actually $body is initialized with NULL when not suppplied to the function. It should be easily fixed with something like this:
```
<?php
if ($body) {
    foreach($body as $key => $val) {
        if($val === null) {
            unset($body[$key]);  
        }
    }
}
```

**Comment by short-pixel-optimizer** [comment]
Thanks @csaggo for this. Fixed by commit https://github.com/short-pixel-optimizer/shortpixel-php/commit/8ddbdda375dc82c1f6623d3e9acc8ac7177fc6c4
