### ISSUE TITLE
fromBuffer -> toBuffer

### ISSUE THREAD

**Issue by nam-co** [short-pixel-optimizer/shortpixel-php#20]
Hello, thanks for the work on this package, I was wondering if its possible to get the optimize image on a variable instead of putting it in a temporary file?

something like:
```
//Compress from an image in memory
$myImage = file_get_contents($pathTo_shortpixel.png);
ShortPixel\fromBuffer('shortpixel.png', $myImage)->wait(300)->toBuffer($myImageNew);
```

Also, what is the best way to use this package with Laravel?

Thanks, ShortPixel does an excellent job

**Comment by short-pixel-optimizer** [comment]
A new method toBuffers() was added, please check the new example in the readme. Thanks for your patience!
