### ISSUE TITLE
Add cmd file to vendors bin folder

### ISSUE THREAD

**Issue by bobmulder** [short-pixel-optimizer/shortpixel-php#24]
Hi guys,

To get Shortpixel running from my terminal I've found [this](https://shortpixel.com/cli-docs) guide which tells me to DOWNLOAD the reepository, and use `cmdShortpixelOptimize.php` in the `lib` folder.

when you `composer install` tools like Psalm or PHPUnit, you can call their command tool like `vendor/bin/psalm` or `vendor/bin/phpunit`.

Have you been thinking about adding the cmd script to the bin folder as documented [here](https://getcomposer.org/doc/articles/vendor-binaries.md)? It would get easier to use the binary script of shortpixel.

**Comment by short-pixel-optimizer** [comment]
Created it in the 1.8.6 release, thanks @bobmulder  for the tip!
