### ISSUE TITLE
Duplicate file error on platform with case-insensitive filesystem

### ISSUE THREAD

**Issue by dnabeast** [short-pixel-optimizer/shortpixel-php#25]
Requiring version 1.8.6 on a Mac returns the error 'The archive may contain identical file names with different capitalization (which fails on case insensitive filesystems)'

I suspect it's getting confused about the shortpixel file and the ShortPixel directory name.

**Comment by sebastianthulin** [comment]
Also experiencing this issue on Mac requiring 1.8.6.
