### ISSUE TITLE
\lib\shortpixel file is creating all sorts of issues for us

### ISSUE THREAD

**Issue by shrocktech** [short-pixel-optimizer/shortpixel-php#26]
\lib\shortpixel file is creating all sorts of issues for us when we try to install via composer and even extract the zip, keeps giving us an error file ShortPixel file exists., etc (see attached)
![error](https://user-images.githubusercontent.com/85584843/143146000-b3b0a45f-b18d-4435-834b-c26b66acf388.png)
![error2](https://user-images.githubusercontent.com/85584843/143146156-89ede2ca-c723-43ee-9d19-80dc04ed53e8.png)

![error3](https://user-images.githubusercontent.com/85584843/143146420-79b0017a-4675-4b4c-b746-043df1015367.png)

**Comment by short-pixel-optimizer** [comment]
Thanks @shrocktech for reporting and @JamesFreeman for fixing this. Fix merged into v1.8.7.

**Comment by shrocktech** [comment]
Thanks for the quick response I will check it out shortly!

**Comment by shrocktech** [comment]
All is working well, thanks again!
