### ISSUE TITLE
Warning: preg_match(): Compilation failed: missing closing parenthesis at offset 16

### ISSUE THREAD

**Issue by Bligivi** [short-pixel-optimizer/shortpixel-php#27]
Hello !

My PHP trigger an error when I tried to use your library on a Symfony 5 environment :

Windows 10
WampServer 3.2.5
PHP 7.4
Version 1.8.5
File : Result.php
Function : toFiles()

Problem :

PHP Error - missing parenthesis on regex `preg_match('/^[a-zA-Z]:(\/|\\)/', $path)`

Lines : 
46
```
if(   (strtoupper(substr(PHP_OS, 0, 3)) === 'WIN' && preg_match('/^[a-zA-Z]:(\/|\\)/', $path) === 0) //it's Windows and no drive letter X:
     || (strtoupper(substr(PHP_OS, 0, 3)) !== 'WIN' && substr($path, 0, 1) !== '/')) { //it's not Windows and doesn't start with a /
                $path = SPTools::trailingslashit(ShortPixel::opt("base_path") ?: $thisDir) . $path;
}
```

Have a good day.

**Comment by short-pixel-optimizer** [comment]
Thanks @Bligivi for reporting. Fixed with v1.8.7.
