### ISSUE TITLE
fromFolder() : trying to get property 'files' of non-object

### ISSUE THREAD

**Issue by Bligivi** [short-pixel-optimizer/shortpixel-php#30]
Hello.

I was trying your example code "A simple loop to optimize all images from a folder" (from the Readme) and I saw this error.

Windows 10
WampServer 3.2.5
PHP 7.4
Version 1.8.7
File : Source.php
Function : fromFolder()

Problem :

PHP Error - Trying to get property 'files' of non-object 
`$paths->files`
$paths is an array which contains all images paths ; it is not an object in my case.

Lines :
95

```
$paths = $persister->getTodo($path, $maxFiles, $exclude, $persistFolder, $maxTotalFileSize, $recurseDepth);
if($paths) {
    ShortPixel::setOptions(array("base_source_path" => $path));
    return $this->fromFiles($paths->files, null, $paths->filesPending);
}
```

Have a good day.

PS: thanks to Gerard B. for the free credits in order to test your library :)

**Comment by short-pixel-optimizer** [comment]
Hi @Bligivi sorry that this issue got somehow under our radar.... :( I can't find in our readme the code you mention, "$paths->files" but hopefully you sorted it out in the meantime... If not please give me more details and reopen the issue. Thanks!

**Comment by Bligivi** [comment]
Hello @short-pixel-optimizer !

I still have the error when I want to use the fromFolder() function `Notice: Trying to get property 'files' of non-object`
Sorry for my response time, I haven't had a chance to test it since your post.

Well, the `$paths->files` is written on my first message :

File : Source.php
Function : fromFolder()
Lines : 95
```return $this->fromFiles($paths->files, null, $paths->filesPending);```

It is on the function call.
The problem still here on the 1.8.8 version.

Have a good day.

**Comment by short-pixel-optimizer** [comment]
@Bligivi I'm not able to reproduce the issue, could you please add a line in the code where the issue is and let me know what it outputs? Just before the error line:
var_dump($paths);
Thanks!

**Comment by Bligivi** [comment]
Hello @short-pixel-optimizer,

Here you have :)

The function to optimize all images from a folder. It is the same that the one on the Readme :
```
\ShortPixel\setOptions(['persist_type' => true]);
$stop = false;
while (!$stop) {
    $ret = \ShortPixel\fromFolder(/from/path)->wait()->toFiles(/to/path);
    if (0 == count($ret->succeeded) + count($ret->failed) + count($ret->same) + count($ret->pending)) {
        $stop = true;
    }
}
```

Here you have the var_dump : 
```
array(4) {
  [0]=>
  string(57) "C:\wamp64\www\test/public/images/diaporama/1-original.jpg"
  [1]=>
  string(48) "C:\wamp64\www\test/public/images/diaporama/1.jpg"
  [2]=>
  string(62) "C:\wamp64\www\test/public/images/diaporama/1-pool-original.jpg"
  [3]=>
  string(53) "C:\wamp64\www\test/public/images/diaporama/1-pool.jpg"
}
```

The error : 
```
In Source.php line 95:                                         
Notice: Trying to get property 'files' of non-object  
```

The source of the problem (with the var_dump) : 
```
$paths = $persister->getTodo($path, $maxFiles, $exclude, $persistFolder, $maxTotalFileSize, $recurseDepth);
var_dump($paths);
if($paths) {
    ShortPixel::setOptions(array("base_source_path" => $path));
    return $this->fromFiles($paths->files, null, $paths->filesPending);
}
```

In this case $paths is an array, not an object, you cannot do : $paths->files.

Have a nice day.

**Comment by simondud** [comment]
Hey @Bligivi sorry it took so long to answer, the problem is when you set the persist type = true and not to 'text', can you please point me to the readme section that contains that wrong example, to correct it? I've also added a check for this in the code because until now passing true would select an obsolete persister that indeed throws the error.
