### ISSUE TITLE
Client not returning server errors (feature request)

### ISSUE THREAD

**Issue by kashmiry** [short-pixel-optimizer/shortpixel-php#31]
Thank you for everyone contributing to this amazing package.
Today the shortpixel service seems to be down.
This php client seems to be returning no errors for this issue **the script keeps on running until 503 error from my server**, for the job is taking too long.
**It would be helpful if its possible for the client to return errors when they are present.**

Currently when I call `https://api.shortpixel.com/v2/reducer.php`
I get a response of
``{"Status":{"Code":"-500","Message":"API is in maintenance mode. Please come back later.","Level":4}}``

I see the package has[ this part](https://github.com/short-pixel-optimizer/shortpixel-php/blob/e469fd2f821c3df9715930cb1466cbd5cd329b43/lib/ShortPixel/Result.php#L97C1-L101C1) which seems to be responsible for returning the errors, but for some reason its not.
````
//check API key errors
if(isset($items->Status->Code) && $items->Status->Code < 0) {
   throw new AccountException($items->Status->Message, $items->Status->Code);
}
````

**Comment by simondud** [comment]
@kashmiry the behaviour is intended as usually a -500 Maintenance mode status doesn't stay for long and it's better especially for the cron jobs usage to wait for it to pass, so the library is designed to wait on transient errors like this one. If you have a use-case when this is not helpful, please reopen this ticket and describe it and will think of a solution. A possibility would be to add an option for this. Thanks!
