### ISSUE TITLE
.git folder when installing with composer

### ISSUE THREAD

**Issue by giovanne3u** [short-pixel-optimizer/shortpixel-php#7]
Hey guys !
Here is my issue, after installing with composer I noticed that the files didn't push on my remote git, so I looked in the `vendor/shortpixel/shortpixel-php` folder and seen a .git folder. Could this .git folder be the source of my problem ?

**Comment by short-pixel-optimizer** [comment]
Hello,
Usually it's not recommended to commit also the dependencies, if you use composer. But if you really need to push the shortpixel/shortpixel-php dependency, just remove the .git folder.
