### ISSUE TITLE
Release

### ISSUE THREAD

**Issue by mnabialek** [short-pixel-optimizer/shortpixel-php#8]
It seems you haven't released recent versions. There is only single release here: https://github.com/short-pixel-optimizer/shortpixel-php/releases (1.4.1) version but it seems there is already 1.5.2 version - https://github.com/short-pixel-optimizer/shortpixel-php/commit/852dfa14e3eaabc3fb0dab06655c79ecb684ae82

**Comment by simondud** [comment]
Thanks a lot for the heads up. Just published it now.
